### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by lfarah** [EranBoudjnah/MTCircularSlider#1]
Hey @EranBoudjnah, your slider library is awesome and I really liked your `Readme.md`. The only thing you're missing is a description.

![screen shot 2016-06-01 at 7 19 20 pm](https://cloud.githubusercontent.com/assets/6511079/15731954/daf23ec0-282d-11e6-8c64-2b102da49955.png)

**Comment by EranBoudjnah** [comment]
Thanks, @lfarah ! Not sure how I missed that! Fixed.

**Comment by max-rosenblattl** [comment]
Hi is it possible to make the slider infinite?

**Comment by EranBoudjnah** [comment]
Hi @Marolicious - it is possible, but will take some time. May get to it over the weekend. No promises!

**Comment by max-rosenblattl** [comment]
My sincerest gratitude! @EranBoudjnah

**Comment by EranBoudjnah** [comment]
Check the winding functionality. You could set it to values greater than 1 to have semi-infinite controls.
