### ISSUE TITLE
Implementation code help for a newbie

### ISSUE THREAD

**Issue by felgarte** [EranBoudjnah/MTCircularSlider#11]
Hello and congrats for the idea, is really useful!
I'm newbie in Xcode environment, and I need to know what's mean "self.slider" and "self.sliderArea".
I add IBAction for UISlider in my ViewController.swift but I know this is not the entire work.
Does anybody can help me? Thanks!

**Comment by EranBoudjnah** [comment]
sliderArea in the demo is just the container of a slider component. self.slider is the slider component itself. I hope this helps!
