### ISSUE TITLE
 Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored

### ISSUE THREAD

**Issue by Ruthwick** [EranBoudjnah/MTCircularSlider#12]

**Comment by pj-wilson** [comment]
are you trying to play audio using this?

**Comment by Ruthwick** [comment]
Hi,
Thanks for the reply. No im not playing any value. Im just using it to show
the value.

**Comment by EranBoudjnah** [comment]
More information could help here. What value are you passing in that is causing this behaviour?

**Comment by Ruthwick** [comment]
Hi,
Sorry for the late reply. I am actually trying to pass the range which the
user choose between two values. I have added constraints for the view. I
works fine in a iphone 6 screen but when i try to run it in a iphone 5
device it doesnt show the knob for the slider and also the track tint
colour disappears. I have tried changing the constraints but still the view
fails to load.

**Comment by EranBoudjnah** [comment]
I'd suspect the resulting view is too small and this breaks the math. It'll take me at least a week to find the time to look into it, though, I'm afraid. In the meantime you could try making sure the widget is not confined to too small a space.

**Comment by Ruthwick** [comment]
Thank you for the suggestion. I have done a temporary fix by setting frame
for each screen size programmatically.
