### ISSUE TITLE
UIControlEvents.valueChanged stops audio playing

### ISSUE THREAD

**Issue by pj-wilson** [EranBoudjnah/MTCircularSlider#13]
Even when is declared in target it stops audio playing though AVPlayer

self.circleSpinner.addTarget(self, action: #selector(PlayerViewController.circleSpinnerAction), for: UIControlEvents.valueChanged)

audio just will not play

**Comment by EranBoudjnah** [comment]
Why would you expect this to play sound? What, that is specific to this component, is not behaving as expected?

**Comment by varunDM** [comment]
@pupoo Yes. It stops the audio. Did you resolved the issue?

**Comment by varunDM** [comment]
@EranBoudjnah There is an issue.  .valueChanged event is being repeatedly send.

**Comment by varunDM** [comment]
@pupoo The issue is you may be changing the slider value with the audioplayer time and then again seeking the audioplayer with the change in the slider value. These 2 contradicts and the audioplayer stucks at the same time. Got it?
