### ISSUE TITLE
"Failed to render and update auto layout status" error

### ISSUE THREAD

**Issue by bcichowlas** [EranBoudjnah/MTCircularSlider#14]
error: IB Designables: Failed to render and update auto layout status for FirstViewController (9pv-A4-QxB): dlopen(MTCircularSlider.framework, 1): no suitable image found.  Did find:
	MTCircularSlider.framework: required code signature missing for 'MTCircularSlider.framework'

So far it doesn't seem to affect anything.  I am on Xcode 9.4.1

**Comment by EranBoudjnah** [comment]
Hi @bcichowlas - thanks for the feedback! This seems to be a known issue: https://github.com/CocoaPods/CocoaPods/issues/7606
