### ISSUE TITLE
line cap style doesnt work

### ISSUE THREAD

**Issue by vishnu-cz** [EranBoudjnah/MTCircularSlider#17]
I want rounded edges for the arc, but .lineCap = .round isnt working. Please help

**Comment by EranBoudjnah** [comment]
Because of the way the track is currently drawn, there is no way to set its cap, sadly. (See drawTrack() to see why. Basically a mask is used, drawing two arcs and lines between them. What you want is for these lines to be round, which is quite a challenging task!)
