### ISSUE TITLE
slider in a scroll view misbehaves

### ISSUE THREAD

**Issue by ghost** [EranBoudjnah/MTCircularSlider#18]
I have the circular slider inside a scroll view. tapping to change the value works but dragging it, 95% of the time the scroll view moves, not the slider.

**Comment by ghost** [comment]
tried making the border thicker, clear color - didn't register touch on the border it seems ... no luck :-(

**Comment by EranBoudjnah** [comment]
Are you trying on the simulator or on device? The border would not affect the touch area of the thumb - only the thumb radius would.

**Comment by ghost** [comment]
physical device. A radius of 42 will look bad, but a clear touchable thicker border will serve the purpose of apple's guidelines for a touch area being at least 42 points, without looking bad.

**Comment by EranBoudjnah** [comment]
Released a new version with touchPadding support. Thank you for your feedback!

**Comment by ghost** [comment]
Thanks a lot!!

**Comment by ghost** [comment]
Any reason why minimum deployment went from iOS version 12.0 to 12.2?

**Comment by EranBoudjnah** [comment]
Not really. Xcode must have updated it automatically at some point since the last release (which was quite a while ago!)

**Comment by naclcaleb** [comment]
From my CocoaPods installation, the touch padding isn't there. Has the new version not been released there yet or something?
