### ISSUE TITLE
Value issue when taping outside of a partial slider

### ISSUE THREAD

**Issue by Ezor** [EranBoudjnah/MTCircularSlider#2]
Hi,

When using a partial Slider as the one in the demo project (the one in the top right corner), if you tap outside of the slider (i.e. tap at the location of the star as shown in the attached screenshot), the value is set to max value.

![slider](https://cloud.githubusercontent.com/assets/14620/15991768/f908bdca-30bc-11e6-8c7b-64b06449ba90.png)

**Comment by EranBoudjnah** [comment]
Thanks, @Ezor! What would you suggest the expected behaviour to be? Should I limit the gesture to only start on the slider itself?

**Comment by Ezor** [comment]
Yes limit the gesture to the slider itself would be perfect.

Currently cause of my big finger when i try to move the thumb from the min value, the slider moves directly to the max value :(

**Comment by EranBoudjnah** [comment]
Big finger patch in place!

**Comment by Ezor** [comment]
Well thanks that was fast and this is almost perfect but now it's quite difficult to start dragging the thumb if the arc is thin (my big finger again maybe).
Maybe you could add some sort of "padding" around the arc when detecting if a touch is in the arc (or use the thumb width) ?

**Comment by EranBoudjnah** [comment]
That's odd and not at all expected - the radius and thickness of the arc are not factors in capturing a gesture... Can you maybe narrow down the problem a bit more?

**Comment by Ezor** [comment]
![image](https://cloud.githubusercontent.com/assets/14620/15993508/cbddb43c-30e8-11e6-8766-ce1b0a6e7361.jpeg)

Here is my sliders. For the left slider (min value) if I put my finger on the lower right part of the thumb (so that the touch is outside of the arc) it became impossible to drag the thumb. Same for the right slider (at max value) if I start dragging with my finger in the bottom left corner of the thumb (point outside of the arc)

Sorry if my approximative emglish and it's hard to understand ;)

**Comment by EranBoudjnah** [comment]
Your English is absolutely fine. Thank you for the screenshots. It should now work as you'd expect!

**Comment by Ezor** [comment]
Sorry for the delay ! It works really great thank you very much !!

**Comment by EranBoudjnah** [comment]
My pleasure :)
