### ISSUE TITLE
Slider triggers interactive dismissal in iOS 13

### ISSUE THREAD

**Issue by naclcaleb** [EranBoudjnah/MTCircularSlider#20]
In iOS 13, the new modal presentation style has an interactive dismissal feature that allows you to swipe down to dismiss the view controller. 
Trying to drag the slider in a presented view controller also triggers this dismissal, making it basically impossible to use.

**Comment by EranBoudjnah** [comment]
Thanks for flagging this. This isn't really a widget problem. However, you can work around the problem by using `isModalInPresentation`. You can turn it on permanently or maybe do something fancy like toggling it on when the widget is interacted with and off afterwards.

See here: https://stackoverflow.com/questions/56459329/disable-the-interactive-dismissal-of-presented-view-controller-in-ios-13

**Comment by naclcaleb** [comment]
That doesn't work either, because it will still start scrolling, it just won't let you scroll it all the way down.

**Comment by EranBoudjnah** [comment]
Have you tried `.modalPresentationStyle = .fullScreen`? I'd suggest disabling the breaking behavior while the widget is being interacted with. I'm not sure how other components address this. Fir example, vertical sliders?

**Comment by naclcaleb** [comment]
The `.fullScreen` presentation style is my current workaround. In my case it's fine, but it would still be nice to have it work in the page sheet.

I don't know how other components do it either; I'm not very experienced with this kind of thing.
