### ISSUE TITLE
Install Version 1.2.0  not 1.0.0 

### ISSUE THREAD

**Issue by Yancerva** [EranBoudjnah/MTCircularSlider#25]
![Captura de Pantalla 2021-07-08 a la(s) 19 10 10](https://user-images.githubusercontent.com/26231774/125005917-8b915700-e022-11eb-9e5d-5ef5f27df716.png)
I have already Xcode 12.5.1 ,
pod version -> 1.10.1'

the version pod install always 1.0.0 but I need the 1.2.0 

in podFile Specs have

"# Uncomment the next line to define a global platform for your project"
platform :ios, '12.0'

target 'MyAppTarget' do
  "# Comment the next line if you're not using Swift and don't want to use dynamic frameworks"
  use_frameworks!

pod  'MTCircularSlider '

end

the version 1.0.0 do not have the attribute  areTrackCapsRound, is there another way to set the corners for the trackPath? not the thumb....

**Comment by EranBoudjnah** [comment]
Sorry, I'm not clear on why you want to use an older version with newer features. What's the reason?

**Comment by Yancerva** [comment]
I need the newest version... but the pod install the older, sorry for not being clear, recently update the title ajajjaa,

**Comment by EranBoudjnah** [comment]
Can you check if the solutions suggested here help?

https://stackoverflow.com/questions/45306087/cocoapods-is-installing-old-pod-version

**Comment by Yancerva** [comment]
the problem is for the support target in the pod file and the last version doesn't have support for the version 12.0, can create support for the target version 12.0? because the last version install from target platform: 12.2, and my project need target from 12.0 sorry for the trouble!, because I have another frameworks, custmized for the client and specify the project need Support target from 12.0.

for example this occurred, but with my compile is in 12.0

![Captura de Pantalla 2021-07-09 a la(s) 13 15 02](https://user-images.githubusercontent.com/26231774/125120173-ba0d4180-e0b7-11eb-9344-a5652003f57d.png)


if I try install using   pod 'MTCircularSlider', '~> 1.2.0'

![Captura de Pantalla 2021-07-09 a la(s) 13 17 13](https://user-images.githubusercontent.com/26231774/125120368-fb055600-e0b7-11eb-9272-6c45cf4abb53.png)

**Comment by Yancerva** [comment]
Or if there is a possibility that this modification can be made? If possible, give me permission to do it, sorry for the inconvenience, the component is great and I have not found another that meets the customer's requirements.

**Comment by EranBoudjnah** [comment]
You're welcome to create a branch, make the change and raise a PR :)

**Comment by Yancerva** [comment]
Hello! Thanks a lot!, I send connection in LinkedIn, I'm Adrian Francisco Cervantes I will send my email   in a message there, I need  permitions to send push to branch, Thanks A lot again!! regards!

**Comment by EranBoudjnah** [comment]
I believe this is now sorted?
