### ISSUE TITLE
Changing value of slider

### ISSUE THREAD

**Issue by lfarah** [EranBoudjnah/MTCircularSlider#6]
I'm building a video editing app and I'm using MTCircularSlider to set the current time in the video.
The problem is that since it is a video, I set the .value a lot of times per second and MTCircularSlider can't handle.
I found a quick fix by deleting the `sendActions(for: .valueChanged)` and now it works perfectly.
### Before:

``` swift
    @IBInspectable
    public var value: Float = 0.5 {
        didSet {
            let cappedVal = cappedValue(value: value)
            if value != cappedVal { value = cappedVal }
            setNeedsDisplay()

            sendActions(for: .valueChanged)
        }
    }
```
### After

``` swift
    @IBInspectable
    public var value: Float = 0.5 {
        didSet {
            let cappedVal = cappedValue(value: value)
            if value != cappedVal { value = cappedVal }
            setNeedsDisplay()
        }
    }
```

**Comment by lfarah** [comment]
And I put the `sendActions()` there:

``` swift
override
    public func continueTracking(_ touch: UITouch,
                                 with event: UIEvent?) -> Bool {
        if !hasThumb {
            return super.continueTracking(touch, with: event)
        }

        let location = touch.location(in: self)

        value = calculatePseudoValue(from: lastPositionForTouch, to: location)

        lastPositionForTouch = location
        sendActions(for: .valueChanged)

        return true
    }
```

**Comment by EranBoudjnah** [comment]
Without seeing your code I can't say for certain, but that seems to me like a problem with how you use the control. If your code handling value changes is performance-heavy, and you have no flag set to indicate you manually set the value (say, several times a second) and so should do nothing with the valueChanged event - your code may be triggered which may be slow. Your fix will not notify your code if the value was changed externally, nor when the user taps to change the value.

Please let me know if this answers your question and the issue can be closed.
